version: '3.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crypto-simulator

  main:
    depends_on:
      - "db"
    links:
      - "db"
    image: mathisburger/crypto-simulator:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      APPLICATION_PORT: 8080
      RATE_LIMITER: enabled
      DATABASE_USER: test
      DATABASE_PASSWORD: password
      DATABASE_HOST: db:3306
      DATABASE_NAME: crypto-simulator
      DEPRECATED_ENDPOINTS: disabled
volumes:
  db_data: {}